# Generated by Django 3.2.9 on 2021-12-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_events_games_gametypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametypes',
            old_name='gametype',
            new_name='label',
        ),
    ]
