# Generated by Django 3.2.9 on 2021-12-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_rename_gametype_gametypes_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gametypes',
            new_name='Gametype',
        ),
    ]
