# Generated by Django 3.2.9 on 2022-01-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_rename_game_event_gameid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gameId',
            new_name='game',
        ),
    ]
