# Generated by Django 3.2.9 on 2021-12-21 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levelupapi', '0004_rename_gametypes_gametype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('gamer', models.CharField(max_length=55)),
                ('game_type', models.CharField(max_length=55)),
                ('number_of_players', models.IntegerField()),
                ('skill_level', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
