# Generated by Django 3.2.9 on 2022-01-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0006_rename_gameid_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(related_name='attending', to='levelupapi.Gamer'),
        ),
    ]
